import type { UiSnapshot } from './types';

export const mockUiSnapshot: UiSnapshot = {
  login: {
    title: 'ログイン',
    description:
      'ログイン必要情報はメールアドレスとパスワードの 2 項目です。認証処理は未接続で、後から Laravel の認証 API に差し替えます。',
    fields: ['メールアドレス', 'パスワード'],
  },
  ledger: {
    summaryCards: [
      { label: '今月の収入', value: '¥320,000', note: '給与と副収入の仮データ' },
      { label: '今月の支出', value: '¥186,400', note: '固定費と変動費の仮データ' },
      { label: '差引残高', value: '¥133,600', note: 'サーバー連携時に自動計算へ差し替え' },
    ],
    transactions: [
      { id: 1, date: '2026-03-21', category: '食費', detail: 'スーパー', amount: '- ¥4,820', type: 'expense' },
      { id: 2, date: '2026-03-20', category: '給与', detail: '月次入金', amount: '+ ¥280,000', type: 'income' },
      { id: 3, date: '2026-03-19', category: '交通費', detail: '定期券チャージ', amount: '- ¥8,000', type: 'expense' },
      { id: 4, date: '2026-03-18', category: '趣味', detail: '書籍購入', amount: '- ¥2,200', type: 'expense' },
      { id: 5, date: '2026-03-17', category: '住居費', detail: '家賃引き落とし', amount: '- ¥78,000', type: 'expense' },
    ],
    monthlyBudgets: [
      { category: '食費', used: '¥32,400', budget: '¥45,000', progress: 72 },
      { category: '住居費', used: '¥78,000', budget: '¥78,000', progress: 100 },
      { category: '娯楽', used: '¥12,000', budget: '¥20,000', progress: 60 },
      { category: '交通費', used: '¥8,000', budget: '¥15,000', progress: 53 },
      { category: '給与', used: '¥280,000', budget: '¥300,000', progress: 93 },
    ],
    categoryInsights: {
      食費: {
        category: '食費',
        consumptionStatus: '予算の 72% を消費中',
        usageRate: '残り予算は ¥12,600',
        trend: '先週比 +8%',
        trendNote: '外食回数が増えており、やや上振れ傾向です。',
        assetValue: '¥1,486,200',
        assetDelta: '- ¥32,400',
        highlight: '食費が資産を緩やかに圧迫しています。',
      },
      住居費: {
        category: '住居費',
        consumptionStatus: '予算をちょうど消化済み',
        usageRate: '固定費として確定済み',
        trend: '前月比 ±0%',
        trendNote: '住居費は毎月一定で、増減は発生していません。',
        assetValue: '¥1,440,600',
        assetDelta: '- ¥78,000',
        highlight: '大きな固定費として資産残高へ直接反映されています。',
      },
      娯楽: {
        category: '娯楽',
        consumptionStatus: '予算の 60% を消費中',
        usageRate: '余力は ¥8,000',
        trend: '先週比 -12%',
        trendNote: '今週は支出が落ち着いており、消費ペースは減少中です。',
        assetValue: '¥1,506,600',
        assetDelta: '- ¥12,000',
        highlight: '抑制できており、資産への影響は限定的です。',
      },
      交通費: {
        category: '交通費',
        consumptionStatus: '予算の 53% を消費中',
        usageRate: '残り予算は ¥7,000',
        trend: '前週比 +3%',
        trendNote: '移動回数の増加により、軽微に増加しています。',
        assetValue: '¥1,510,600',
        assetDelta: '- ¥8,000',
        highlight: '現時点では許容範囲で推移しています。',
      },
      給与: {
        category: '給与',
        consumptionStatus: '今月の入金予定の 93% を反映',
        usageRate: '未反映予定額は ¥20,000',
        trend: '前月比 +5%',
        trendNote: '副収入込みで前月より増加しています。',
        assetValue: '¥1,588,600',
        assetDelta: '+ ¥280,000',
        highlight: '資産総額を最も押し上げている主要項目です。',
      },
    },
  },
  ledgerCreate: {
    title: '家計簿状況の追加ページ',
    description: '新しい家計簿データを追加するための専用ページです。現在は UI のみ実装しています。',
    defaultDate: '2026-03-24',
    defaultType: 'expense',
    defaultCategory: 'food',
  },
};
